FIX Remove mapping _type field
It used to generate errors like (probably due to the bulk writes):
```
[2020-01-15T17:33:57,119][DEBUG][o.e.a.b.TransportShardBulkAction] [xxxx] [metrics-2020-01-15][0] failed to execute bulk item (index) index {[metrics-2020-01-15][metric][aTpEqm8BcUPu4pjv2yT4], source[{"value":35.0,"hostname":"xxxx","http_status_code":200,"timestamp":"2020-01-15T17:33:56.108763","name":"api.views.AnswerView.create"}]}
java.lang.IllegalArgumentException: Rejecting mapping update to [metrics-2020-01-15] as the final mapping would have more than 1 type: [_doc, metric]
```